tasks:
  - init: pip install -r requirements.txt
    command: flask init & flask run

ports:
  - port: 8080
    onOpen: open-browser
    visibility: public
image:
  file: .gitpod.Dockerfile

# github:
#   prebuilds:
#     master: true
#     branches: false
#     pullRequests: true
#     addCheck: true
#     addComment: true
